### ISSUE TITLE
Logo should be clickable

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/dmse-documentation#11]
A click to the log should take the user back to the Github pages website.
We don't have a link for it yet but we can link back to the same page https://openmobilealliance.github.io/dmse-documentation/ 

![image](https://user-images.githubusercontent.com/3258579/124057144-cb7d8c00-d9db-11eb-93ef-6f15c7d0e868.png)

**Comment by jpradocueva** [comment]
@ladyvargas remember to link the commit or pull request with the issue.
The work is completed but I don't see what code has been changed. Could you please add a link to the PR or commit? Thanks

**Comment by ladyvargas** [comment]
#9

**Comment by jpradocueva** [comment]
ok, to close
