### ISSUE TITLE
Add links to media icons

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/dmse-documentation#4]
Twitter  --> https://twitter.com/OMASpecWorks
GitHub --> https://github.com/OpenMobileAlliance
LinkedIn --> https://www.linkedin.com/company/open-mobile-alliance/?viewAsMember=true
YouTube --> https://www.youtube.com/c/OMASpecWorks

**Comment by jpradocueva** [comment]
Still missing:
LinkedIn --> https://www.linkedin.com/company/open-mobile-alliance/?viewAsMember=true
YouTube --> https://www.youtube.com/c/OMASpecWorks

**Comment by rubystream** [comment]
@jpradocueva The media icons are added. Please review.

**Comment by jpradocueva** [comment]
@rubystream it works beautifully, thanks!
