### ISSUE TITLE
https://guidelines.openmobilealliance.org/testfests/ web page has broken links

### ISSUE THREAD

**Issue by jmudge** [OpenMobileAlliance/dmse-documentation#42]
As discussed, when using the web site https://guidelines.openmobilealliance.org/ and navigating to the "TestFests - Workshops" page initially URL (2) is displayed (see below) . However if this web page is refreshed then URL (1) is displayed (see below).

1. https://guidelines.openmobilealliance.org/testfests/
Displays a web page that includes "Product Listing Webpage" links with URLs https://guidelines.openmobilealliance.org/testfests/listing . When these latter links are clicked on then "my first nuxt project" is briefly shown in the browser tab, followed by the web page error message "Page not found".

2. https://guidelines.openmobilealliance.org/testfests
The "Product Listing column" displays page icons with the URL "https://guidelines.openmobilealliance.org/listing" and these links work.

It is surprising that the above URLs (1) and (2) generate such different results. When browsing the web site both pages with URLs (1) and (2) can be legitimately generated (no URL editing is necessary). Of course only URL (2) displays pages that work properly.

The above behaviour is exhibited with both Firefox and Chrome.

Please can this issue be resolved?

**Comment by jpradocueva** [comment]
@rubystream and @jmudge problem has been resolved. The issue was to prefix the link to the product listing with '.' as in './listing' rather than '/listing'.

See changes https://github.com/OpenMobileAlliance/dmse-documentation/commit/281386ce6ef163cc08006f686f5c1115487487d8
