### ISSUE TITLE
Enlarge the text area

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/dmse-documentation#8]
* Enlarge text area or
* Add scrolls (vertical or horizontal) 

![image](https://user-images.githubusercontent.com/3258579/123685488-9b7b9080-d803-11eb-87b9-a79985c26ab3.png)

**Comment by jpradocueva** [comment]
@ladyvargas remember to link the PR with the issue. The problem has been resolved but it doesn't indicate by which commit or Pull Request. It will be good to have a reference here to the change.

**Comment by ladyvargas** [comment]
#9  [https://github.com/OpenMobileAlliance/dmse-documentation/pull/9/commits/6085d37e21d65dedb379541e823ef455aa2bfb5f](url)

**Comment by ladyvargas** [comment]
#9

**Comment by jpradocueva** [comment]
Ok, to close
